// Verification determinations for kata movement counts.
//
// GENERATED by comparing the repository's Shotokan corpus against a published
// JKA affiliate movement-count table. Do not hand-edit: regenerate, or the
// comparison stops being a comparison and becomes an assertion.
//
// ─────────────────────────────────────────────────────────────────────────────
// WHAT THIS CORRECTED
// ─────────────────────────────────────────────────────────────────────────────
//
// Migration 0031 concluded that per-kata movement counts could not be verified,
// on the strength of reading the JKA's "Technical Manual for the Instructor",
// which requires an examiner to "verify that there is an accurate number of
// movements" but does not publish the counts.
//
// THAT CONCLUSION WAS TOO STRONG, and this file is the correction. The counts
// are published — not in that manual, but in affiliate syllabus material. The
// Chiba Prefecture Headquarters of the JKA publishes a table headed 挙動数
// ("number of movements") listing 25 of the 26 kata with their movement
// count and their kiai positions. It was fetched and parsed directly.
//
// ─────────────────────────────────────────────────────────────────────────────
// WHAT IT FOUND
// ─────────────────────────────────────────────────────────────────────────────
//
// 24 of the corpus's counts are corroborated exactly.
// 1 disagrees: nijushiho (corpus 24, JKA 34).
// 1 is absent from the table entirely: jiin.
//
// 2 kata have a corroborated COUNT but a kiai position the table
// contradicts: kanku-dai (corpus 15/45, JKA 15/65); sochin (corpus 28/41, JKA 30/41).
// Those are recorded in the citation text rather than acted on, because kiai
// are not stored in a column and inventing one to hold a contradiction would be
// the wrong way round.
//
// A disagreement leaves `movementCount` null. Storing either figure would make
// this system the thing that settled a disagreement it has no standing to
// settle — that is the MMAKF technical committee's decision, and when they take
// it the verification moves to 'committee_verified'.

import type { CorpusDetermination } from '@/db/library-seed';

/** The table this file is derived from. */
export const KATA_COUNT_SOURCE = {
  organisation: 'Japan Karate Association, Chiba Prefecture Headquarters',
  url: "https://jkachiba.com/kyodousuu/",
  title: '挙動数 — kata movement counts',
  retrievedOn: "2026-08-17",
} as const;

export const KATA_DETERMINATIONS: readonly CorpusDetermination[] = [
  {
    "slug": "bassai-dai",
    "verification": "source_documented",
    "movementCount": 42,
    "variants": [],
    "citation": {
      "organisation": "Japan Karate Association, Chiba Prefecture Headquarters",
      "url": "https://jkachiba.com/kyodousuu/",
      "quote": "抜塞大 42 (19) (42)"
    },
    "reason": "The JKA Chiba Prefecture Headquarters publishes a movement-count table (挙動数) giving 42 movements, which matches the figure in the repository corpus. The table also gives kiai at 19 and 42."
  },
  {
    "slug": "bassai-sho",
    "verification": "source_documented",
    "movementCount": 27,
    "variants": [],
    "citation": {
      "organisation": "Japan Karate Association, Chiba Prefecture Headquarters",
      "url": "https://jkachiba.com/kyodousuu/",
      "quote": "抜塞小 27 (17) (22)"
    },
    "reason": "The JKA Chiba Prefecture Headquarters publishes a movement-count table (挙動数) giving 27 movements, which matches the figure in the repository corpus. The table also gives kiai at 17 and 22."
  },
  {
    "slug": "chinte",
    "verification": "source_documented",
    "movementCount": 32,
    "variants": [],
    "citation": {
      "organisation": "Japan Karate Association, Chiba Prefecture Headquarters",
      "url": "https://jkachiba.com/kyodousuu/",
      "quote": "珍手 32 (28) (32)"
    },
    "reason": "The JKA Chiba Prefecture Headquarters publishes a movement-count table (挙動数) giving 32 movements, which matches the figure in the repository corpus. The table also gives kiai at 28 and 32."
  },
  {
    "slug": "empi",
    "verification": "source_documented",
    "movementCount": 37,
    "variants": [],
    "citation": {
      "organisation": "Japan Karate Association, Chiba Prefecture Headquarters",
      "url": "https://jkachiba.com/kyodousuu/",
      "quote": "燕飛 37 (15) (36)"
    },
    "reason": "The JKA Chiba Prefecture Headquarters publishes a movement-count table (挙動数) giving 37 movements, which matches the figure in the repository corpus. The table also gives kiai at 15 and 36."
  },
  {
    "slug": "gankaku",
    "verification": "source_documented",
    "movementCount": 42,
    "variants": [],
    "citation": {
      "organisation": "Japan Karate Association, Chiba Prefecture Headquarters",
      "url": "https://jkachiba.com/kyodousuu/",
      "quote": "岩鶴 42 (28) (42)"
    },
    "reason": "The JKA Chiba Prefecture Headquarters publishes a movement-count table (挙動数) giving 42 movements, which matches the figure in the repository corpus. The table also gives kiai at 28 and 42."
  },
  {
    "slug": "gojushiho-dai",
    "verification": "source_documented",
    "movementCount": 67,
    "variants": [],
    "citation": {
      "organisation": "Japan Karate Association, Chiba Prefecture Headquarters",
      "url": "https://jkachiba.com/kyodousuu/",
      "quote": "五十四歩大 67 (59) (66)"
    },
    "reason": "The JKA Chiba Prefecture Headquarters publishes a movement-count table (挙動数) giving 67 movements, which matches the figure in the repository corpus. The table also gives kiai at 59 and 66."
  },
  {
    "slug": "gojushiho-sho",
    "verification": "source_documented",
    "movementCount": 65,
    "variants": [],
    "citation": {
      "organisation": "Japan Karate Association, Chiba Prefecture Headquarters",
      "url": "https://jkachiba.com/kyodousuu/",
      "quote": "五十四歩小 65 (57) (64)"
    },
    "reason": "The JKA Chiba Prefecture Headquarters publishes a movement-count table (挙動数) giving 65 movements, which matches the figure in the repository corpus. The table also gives kiai at 57 and 64."
  },
  {
    "slug": "hangetsu",
    "verification": "source_documented",
    "movementCount": 41,
    "variants": [],
    "citation": {
      "organisation": "Japan Karate Association, Chiba Prefecture Headquarters",
      "url": "https://jkachiba.com/kyodousuu/",
      "quote": "半月 41 (11) (40)"
    },
    "reason": "The JKA Chiba Prefecture Headquarters publishes a movement-count table (挙動数) giving 41 movements, which matches the figure in the repository corpus. The table also gives kiai at 11 and 40."
  },
  {
    "slug": "heian-godan",
    "verification": "source_documented",
    "movementCount": 23,
    "variants": [],
    "citation": {
      "organisation": "Japan Karate Association, Chiba Prefecture Headquarters",
      "url": "https://jkachiba.com/kyodousuu/",
      "quote": "平安五段 23 (12) (19)"
    },
    "reason": "The JKA Chiba Prefecture Headquarters publishes a movement-count table (挙動数) giving 23 movements, which matches the figure in the repository corpus. The table also gives kiai at 12 and 19."
  },
  {
    "slug": "heian-nidan",
    "verification": "source_documented",
    "movementCount": 26,
    "variants": [],
    "citation": {
      "organisation": "Japan Karate Association, Chiba Prefecture Headquarters",
      "url": "https://jkachiba.com/kyodousuu/",
      "quote": "平安二段 26 (11) (26)"
    },
    "reason": "The JKA Chiba Prefecture Headquarters publishes a movement-count table (挙動数) giving 26 movements, which matches the figure in the repository corpus. The table also gives kiai at 11 and 26."
  },
  {
    "slug": "heian-sandan",
    "verification": "source_documented",
    "movementCount": 20,
    "variants": [],
    "citation": {
      "organisation": "Japan Karate Association, Chiba Prefecture Headquarters",
      "url": "https://jkachiba.com/kyodousuu/",
      "quote": "平安三段 20 (10) (20)"
    },
    "reason": "The JKA Chiba Prefecture Headquarters publishes a movement-count table (挙動数) giving 20 movements, which matches the figure in the repository corpus. The table also gives kiai at 10 and 20."
  },
  {
    "slug": "heian-shodan",
    "verification": "source_documented",
    "movementCount": 21,
    "variants": [],
    "citation": {
      "organisation": "Japan Karate Association, Chiba Prefecture Headquarters",
      "url": "https://jkachiba.com/kyodousuu/",
      "quote": "平安初段 21 (9) (17)"
    },
    "reason": "The JKA Chiba Prefecture Headquarters publishes a movement-count table (挙動数) giving 21 movements, which matches the figure in the repository corpus. The table also gives kiai at 9 and 17."
  },
  {
    "slug": "heian-yondan",
    "verification": "source_documented",
    "movementCount": 27,
    "variants": [],
    "citation": {
      "organisation": "Japan Karate Association, Chiba Prefecture Headquarters",
      "url": "https://jkachiba.com/kyodousuu/",
      "quote": "平安四段 27 (13) (25)"
    },
    "reason": "The JKA Chiba Prefecture Headquarters publishes a movement-count table (挙動数) giving 27 movements, which matches the figure in the repository corpus. The table also gives kiai at 13 and 25."
  },
  {
    "slug": "jiin",
    "verification": "unverified",
    "movementCount": null,
    "variants": [],
    "citation": null,
    "reason": "Not listed in the JKA Chiba Prefecture Headquarters movement-count table, which is the source that corroborates the rest of the series. No other authoritative source was verified for this kata, so no count is asserted."
  },
  {
    "slug": "jion",
    "verification": "source_documented",
    "movementCount": 47,
    "variants": [],
    "citation": {
      "organisation": "Japan Karate Association, Chiba Prefecture Headquarters",
      "url": "https://jkachiba.com/kyodousuu/",
      "quote": "慈恩 47 (17) (47)"
    },
    "reason": "The JKA Chiba Prefecture Headquarters publishes a movement-count table (挙動数) giving 47 movements, which matches the figure in the repository corpus. The table also gives kiai at 17 and 47."
  },
  {
    "slug": "jitte",
    "verification": "source_documented",
    "movementCount": 24,
    "variants": [],
    "citation": {
      "organisation": "Japan Karate Association, Chiba Prefecture Headquarters",
      "url": "https://jkachiba.com/kyodousuu/",
      "quote": "十手 24 (13) (24)"
    },
    "reason": "The JKA Chiba Prefecture Headquarters publishes a movement-count table (挙動数) giving 24 movements, which matches the figure in the repository corpus. The table also gives kiai at 13 and 24."
  },
  {
    "slug": "kanku-dai",
    "verification": "source_documented",
    "movementCount": 65,
    "variants": [],
    "citation": {
      "organisation": "Japan Karate Association, Chiba Prefecture Headquarters",
      "url": "https://jkachiba.com/kyodousuu/",
      "quote": "観空大 65 (15) (65)"
    },
    "reason": "The JKA Chiba Prefecture Headquarters publishes a movement-count table (挙動数) giving 65 movements, which matches the figure in the repository corpus. NOTE: the same table gives kiai at 15 and 65, where the repository corpus records 15 and 45. The count is corroborated; the kiai positions are not."
  },
  {
    "slug": "kanku-sho",
    "verification": "source_documented",
    "movementCount": 48,
    "variants": [],
    "citation": {
      "organisation": "Japan Karate Association, Chiba Prefecture Headquarters",
      "url": "https://jkachiba.com/kyodousuu/",
      "quote": "観空小 48 (6) (48)"
    },
    "reason": "The JKA Chiba Prefecture Headquarters publishes a movement-count table (挙動数) giving 48 movements, which matches the figure in the repository corpus. The table also gives kiai at 6 and 48."
  },
  {
    "slug": "meikyo",
    "verification": "source_documented",
    "movementCount": 33,
    "variants": [],
    "citation": {
      "organisation": "Japan Karate Association, Chiba Prefecture Headquarters",
      "url": "https://jkachiba.com/kyodousuu/",
      "quote": "明鏡 33 (32)"
    },
    "reason": "The JKA Chiba Prefecture Headquarters publishes a movement-count table (挙動数) giving 33 movements, which matches the figure in the repository corpus. The table also gives kiai at 32."
  },
  {
    "slug": "nijushiho",
    "verification": "disputed",
    "movementCount": null,
    "variants": [
      {
        "count": 34,
        "organisation": "Japan Karate Association, Chiba Prefecture Headquarters",
        "url": "https://jkachiba.com/kyodousuu/"
      },
      {
        "count": 24,
        "organisation": "MMAKF in-repository Shotokan corpus",
        "url": "repo:src/data/kata.ts"
      }
    ],
    "citation": null,
    "reason": "The JKA Chiba Prefecture Headquarters movement-count table gives 34 movements (二十四歩), while the repository corpus records 24. Both figures are kept and no count is stored, because settling this is the technical committee's decision."
  },
  {
    "slug": "sochin",
    "verification": "source_documented",
    "movementCount": 41,
    "variants": [],
    "citation": {
      "organisation": "Japan Karate Association, Chiba Prefecture Headquarters",
      "url": "https://jkachiba.com/kyodousuu/",
      "quote": "壮鎮 41 (30) (41)"
    },
    "reason": "The JKA Chiba Prefecture Headquarters publishes a movement-count table (挙動数) giving 41 movements, which matches the figure in the repository corpus. NOTE: the same table gives kiai at 30 and 41, where the repository corpus records 28 and 41. The count is corroborated; the kiai positions are not."
  },
  {
    "slug": "tekki-nidan",
    "verification": "source_documented",
    "movementCount": 24,
    "variants": [],
    "citation": {
      "organisation": "Japan Karate Association, Chiba Prefecture Headquarters",
      "url": "https://jkachiba.com/kyodousuu/",
      "quote": "鉄騎二段 24 (16) (24)"
    },
    "reason": "The JKA Chiba Prefecture Headquarters publishes a movement-count table (挙動数) giving 24 movements, which matches the figure in the repository corpus. The table also gives kiai at 16 and 24."
  },
  {
    "slug": "tekki-sandan",
    "verification": "source_documented",
    "movementCount": 36,
    "variants": [],
    "citation": {
      "organisation": "Japan Karate Association, Chiba Prefecture Headquarters",
      "url": "https://jkachiba.com/kyodousuu/",
      "quote": "鉄騎三段 36 (16) (36)"
    },
    "reason": "The JKA Chiba Prefecture Headquarters publishes a movement-count table (挙動数) giving 36 movements, which matches the figure in the repository corpus. The table also gives kiai at 16 and 36."
  },
  {
    "slug": "tekki-shodan",
    "verification": "source_documented",
    "movementCount": 29,
    "variants": [],
    "citation": {
      "organisation": "Japan Karate Association, Chiba Prefecture Headquarters",
      "url": "https://jkachiba.com/kyodousuu/",
      "quote": "鉄騎初段 29 (15) (29)"
    },
    "reason": "The JKA Chiba Prefecture Headquarters publishes a movement-count table (挙動数) giving 29 movements, which matches the figure in the repository corpus. The table also gives kiai at 15 and 29."
  },
  {
    "slug": "unsu",
    "verification": "source_documented",
    "movementCount": 48,
    "variants": [],
    "citation": {
      "organisation": "Japan Karate Association, Chiba Prefecture Headquarters",
      "url": "https://jkachiba.com/kyodousuu/",
      "quote": "雲手 48 (36) (48)"
    },
    "reason": "The JKA Chiba Prefecture Headquarters publishes a movement-count table (挙動数) giving 48 movements, which matches the figure in the repository corpus. The table also gives kiai at 36 and 48."
  },
  {
    "slug": "wankan",
    "verification": "source_documented",
    "movementCount": 24,
    "variants": [],
    "citation": {
      "organisation": "Japan Karate Association, Chiba Prefecture Headquarters",
      "url": "https://jkachiba.com/kyodousuu/",
      "quote": "王冠 24 (24)"
    },
    "reason": "The JKA Chiba Prefecture Headquarters publishes a movement-count table (挙動数) giving 24 movements, which matches the figure in the repository corpus. The table also gives kiai at 24."
  }
];